### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by lululalamm** [chaneyddtt/Generating-Multiple-Hypotheses-for-3D-Human-Pose-Estimation-with-Mixture-Density-Network#4]
Traceback (most recent call last):
  File "predict_3dpose_mdm.py", line 649, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "predict_3dpose_mdm.py", line 643, in main
    test()
  File "predict_3dpose_mdm.py", line 427, in test
    train_set_2d, test_set_2d, data_mean_2d, data_std_2d, dim_to_ignore_2d, dim_to_use_2d = data_utils.read_2d_predictions(actions, FLAGS.data_dir)
  File "/data/3d_pose/generatig-Multiple-hypotheses/src/data_utils.py", line 380, in read_2d_predictions
    train_set = load_stacked_hourglass( data_dir, TRAIN_SUBJECTS, actions)
  File "/data/3d_pose/generatig-Multiple-hypotheses/src/data_utils.py", line 187, in load_stacked_hourglass
    assert loaded_seqs == 8, "Expecting 8 sequences, found {0} instead. S:{1} {2}".format(loaded_seqs, subj, action )
AssertionError: Expecting 8 sequences, found 0 instead. S:1 Directions

error ocuured :(
i run $ python predict_3dpose_mdm.py --test True --load 4338038 --load_dir ../Models/mdm_5_prior/
download pre-trained model , h36m dataset
h36m dataset locate "project_root/data/h36m"

**Comment by lululalamm** [comment]
I think 
problem with src/data_utils.py
